import Feather from "@expo/vector-icons/Feather";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import { SurfaceCard } from "../design/components";
import { colors, radius, spacing, typography } from "../design/theme";
import type { HouseholdProduct } from "./types";

export function ProductCard({ product, onPress }: { product: HouseholdProduct; onPress: () => void }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${product.name}`} onPress={onPress}><SurfaceCard style={styles.card}><View style={styles.imageWrap}>{product.image_url ? <Image accessibilityLabel={`${product.name} photo`} source={{ uri: product.image_url }} style={styles.image} /> : <Feather color={colors.primary} name="package" size={26} />}</View><View style={styles.copy}><Text numberOfLines={1} style={styles.name}>{product.name}</Text>{product.brand ? <Text style={styles.meta}>{product.brand}</Text> : null}<Text style={styles.meta}>{[product.variant, product.size_value && `${product.size_value} ${product.size_unit ?? ""}`].filter(Boolean).join(" · ") || "No size set"}</Text><View style={styles.footer}><Text style={styles.category}>{product.category?.display_name ?? "Uncategorized"}</Text><Text style={styles.usual}>Usually buy {product.usual_quantity}</Text></View></View><Feather color={colors.textSecondary} name="chevron-right" size={20} /></SurfaceCard></Pressable>;
}
const styles = StyleSheet.create({ card: { flexDirection: "row", alignItems: "center", gap: spacing.md, padding: spacing.md }, imageWrap: { width: 68, height: 68, borderRadius: radius.md, backgroundColor: colors.primarySubtle, alignItems: "center", justifyContent: "center", overflow: "hidden" }, image: { width: "100%", height: "100%" }, copy: { flex: 1 }, name: { ...typography.cardTitle, color: colors.text }, meta: { ...typography.secondary, color: colors.textSecondary, marginTop: 2 }, footer: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.sm }, category: { ...typography.caption, color: colors.primary, fontWeight: "700" }, usual: { ...typography.caption, color: colors.textSecondary } });
