import { useState } from "react";
import { useRouter } from "expo-router";
import { StyleSheet, Text, TextInput } from "react-native";
import { AppScreen, BackHeader, InlineError, PrimaryButton, SurfaceCard } from "../src/design/components";
import { colors, radius, spacing, typography } from "../src/design/theme";
import { useHouseholds } from "../src/households/household-context";
import { householdApiClient } from "../src/households/api-client";
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export default function Invite() { const router = useRouter(); const { selected } = useHouseholds(); const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const submit = async () => { const normalizedEmail = email.trim().toLowerCase(); if (selected?.role !== "owner" || !normalizedEmail) return; if (!EMAIL_PATTERN.test(normalizedEmail)) { setError("Enter a valid email address."); return; } setSaving(true); setError(""); try { await householdApiClient.invite(selected.id, normalizedEmail); setSent(true); } catch (e) { setError(e instanceof Error ? e.message : "Couldn’t send this invitation."); } finally { setSaving(false); } }; return <AppScreen keyboardSafe><BackHeader title="Invite member" onBack={() => router.back()} />{sent ? <SurfaceCard><Text style={styles.success}>Invitation sent</Text><Text style={styles.meta}>Sent to {email.trim().toLowerCase()}</Text><PrimaryButton label="Done" onPress={() => router.back()} /></SurfaceCard> : <SurfaceCard><Text style={styles.label}>Email address</Text><TextInput accessibilityLabel="Invite email" autoCapitalize="none" keyboardType="email-address" placeholder="person@example.com" value={email} onChangeText={(value) => { setEmail(value); if (error) setError(""); }} style={styles.input} />{error ? <InlineError message={error} /> : null}<PrimaryButton label="Send invitation" loading={saving} disabled={!email.trim()} onPress={() => void submit()} /></SurfaceCard>}</AppScreen>; }
const styles = StyleSheet.create({ label: { ...typography.bodyStrong, color: colors.text, marginBottom: spacing.sm }, input: { minHeight: 50, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.md, backgroundColor: colors.surface, paddingHorizontal: spacing.md, ...typography.body, color: colors.text, marginBottom: spacing.md }, success: { ...typography.sectionTitle, color: colors.success }, meta: { ...typography.secondary, color: colors.textSecondary, marginTop: spacing.xs } });
