import * as Notifications from "expo-notifications";
import { useEffect, useState } from "react";
import { Platform, StyleSheet, Text } from "react-native";
import { useRouter } from "expo-router";
import { AppScreen, BackHeader, InlineError, PrimaryButton, SecondaryButton, SurfaceCard } from "../src/design/components";
import { colors, spacing, typography } from "../src/design/theme";
import { pushNotificationApi } from "../src/notifications/api-client";
import { registerDeviceForPush } from "../src/notifications/registration";
import { pushStorage } from "../src/notifications/storage";
export default function NotificationsSettings() { const router = useRouter(); const [status, setStatus] = useState<string>("unknown"); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); useEffect(() => { void Notifications.getPermissionsAsync().then(permission => setStatus(permission.status)); }, []); const enable = async () => { setSaving(true); setError(""); try { const id = await registerDeviceForPush(pushNotificationApi, Notifications, Platform.OS === "ios" ? "ios" : "android"); setStatus(id ? "granted" : "denied"); if (!id) setError("Notifications are disabled in system settings."); } catch { setError("Couldn’t enable notifications right now."); } finally { setSaving(false); } }; const disable = async () => { const id = await pushStorage.getTokenId(); if (id) await pushNotificationApi.unregister(id); await pushStorage.clearTokenId(); setStatus("disabled"); }; return <AppScreen><BackHeader title="Notifications" onBack={() => router.back()} /><Text style={styles.intro}>Replacement decisions and requests from your household appear here.</Text><SurfaceCard><Text style={styles.title}>Device status</Text><Text style={styles.status}>{status === "granted" ? "Notifications enabled" : status === "denied" ? "Notifications disabled" : "Permission not requested"}</Text>{error ? <InlineError /> : null}{status === "granted" ? <SecondaryButton label="Turn off notifications" icon="bell-off" onPress={() => void disable()} /> : <PrimaryButton label="Enable notifications" icon="bell" loading={saving} onPress={() => void enable()} />}</SurfaceCard><SurfaceCard><Text style={styles.title}>What you’ll receive</Text><Text style={styles.meta}>Replacement requests needing your approval</Text><Text style={styles.meta}>Approval decisions on requests you sent</Text></SurfaceCard></AppScreen>; }
const styles = StyleSheet.create({ intro: { ...typography.body, color: colors.textSecondary, marginBottom: spacing.lg }, title: { ...typography.cardTitle, color: colors.text }, status: { ...typography.bodyStrong, color: colors.primary, marginTop: spacing.xs, marginBottom: spacing.md }, meta: { ...typography.secondary, color: colors.textSecondary, marginTop: spacing.sm } });
