import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Alert, Pressable, ScrollView, Text, View } from "react-native";

import { useHouseholds } from "../src/households/household-context";
import { listApi } from "../src/lists/api-client";
import { memoryApi, type Memory } from "../src/memory/api-client";

function MemorySection({title,items,onBuy}:{title:string;items:Memory[];onBuy:(item:Memory)=>void}) {
  return <View><Text style={{fontSize:24,fontWeight:"800",marginTop:20}}>{title}</Text>{items.map((item)=><View key={item.household_product_id} style={{padding:14,backgroundColor:"#fff",borderRadius:12,marginTop:10}}><Text style={{fontWeight:"700"}}>{item.name}</Text><Text>{item.brand??""} {item.size_value?`${item.size_value} ${item.size_unit??""}`:""}</Text><Text>{title.startsWith("Frequently")?`Bought ${item.purchase_count} times`:"Recently purchased"}</Text>{item.archived?<Text>Archived household product</Text>:<Pressable onPress={()=>onBuy(item)} style={{marginTop:8}}><Text style={{color:"#245a43",fontWeight:"700"}}>Buy Again</Text></Pressable>}</View>)}</View>;
}

export default function PurchasingMemory(){const {selected}=useHouseholds();const queryClient=useQueryClient();const [buying,setBuying]=useState<Memory|null>(null);const recent=useQuery({queryKey:["households",selected?.id,"purchasing-memory","recent"],queryFn:()=>memoryApi.recent(selected!.id),enabled:!!selected});const frequent=useQuery({queryKey:["households",selected?.id,"purchasing-memory","frequent"],queryFn:()=>memoryApi.frequent(selected!.id),enabled:!!selected});const lists=useQuery({queryKey:["households",selected?.id,"shopping-lists"],queryFn:()=>listApi.lists(selected!.id),enabled:!!selected});const add=useMutation({mutationFn:({listId,productId,quantity}:{listId:string;productId:string;quantity:number})=>listApi.addItem(selected!.id,listId,{household_product_id:productId,requested_quantity:quantity}),onSuccess:async(_,variables)=>{setBuying(null);await queryClient.invalidateQueries({queryKey:["households",selected?.id,"shopping-lists"]});await queryClient.invalidateQueries({queryKey:["households",selected?.id,"shopping-lists",variables.listId]});Alert.alert("Added to shopping list");},onError:()=>Alert.alert("Already on this shopping list")});if(recent.isLoading)return <Text>Loading…</Text>;const recentItems=recent.data?.items??[];const frequentItems=frequent.data?.items??[];if(!recentItems.length&&!frequentItems.length)return <Text style={{padding:24}}>No purchase memory yet.{"\n\n"}Complete a shopping trip and your commonly bought products will appear here.</Text>;return <ScrollView contentContainerStyle={{padding:24,paddingTop:70}}><Text style={{fontSize:30,fontWeight:"800"}}>Purchasing memory</Text><MemorySection title="Recently Purchased" items={recentItems} onBuy={setBuying}/><MemorySection title="Frequently Bought" items={frequentItems} onBuy={setBuying}/>{buying?<View style={{marginTop:20}}><Text style={{fontSize:20,fontWeight:"700"}}>Add {buying.name} to</Text>{lists.data?.map((list)=><Pressable key={list.id} disabled={add.isPending} onPress={()=>add.mutate({listId:list.id,productId:buying.household_product_id,quantity:buying.usual_quantity})} style={{padding:14,backgroundColor:"#245a43",borderRadius:10,marginTop:8}}><Text style={{color:"#fff"}}>{list.name}</Text></Pressable>)}{!lists.data?.length?<Text>No active lists. Create a shopping list first.</Text>:null}</View>:null}</ScrollView>}
