import Feather from "@expo/vector-icons/Feather";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Image, StyleSheet, Text, View } from "react-native";
import { AppScreen, BackHeader, InlineError, LoadingState, PrimaryButton, SecondaryButton, SurfaceCard, TertiaryButton } from "../../src/design/components";
import { formatQuantity, formatSize } from "../../src/design/format";
import { colors, radius, spacing, typography } from "../../src/design/theme";
import { useHouseholds } from "../../src/households/household-context";
import { listApi } from "../../src/lists/api-client";
import { productApi, resolveProductImageUrl } from "../../src/products/api-client";
import { purchasesApi } from "../../src/purchases/api-client";

export default function ProductDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { selected } = useHouseholds(); const qc = useQueryClient();
  const q = useQuery({ queryKey: ["households", selected?.id, "products", id], queryFn: () => productApi.get(selected!.id, id), enabled: Boolean(selected && id) });
  const summary = useQuery({ queryKey: ["households", selected?.id, "products", id, "summary"], queryFn: () => purchasesApi.summary(selected!.id, id), enabled: Boolean(selected && id) });
  const lists = useQuery({ queryKey: ["households", selected?.id, "shopping-lists"], queryFn: () => listApi.lists(selected!.id), enabled: Boolean(selected) });
  const imageUrl = resolveProductImageUrl(q.data?.image_url);
  const [failedImageUrl, setFailedImageUrl] = useState<string>();
  if (q.isLoading) return <AppScreen><LoadingState rows={5} /></AppScreen>;
  if (q.isError || !q.data) return <AppScreen><InlineError onRetry={() => void q.refetch()} /></AppScreen>;
  const product = q.data;
  const add = () => { const list = lists.data?.[0]; if (list) router.push(`/lists/${list.id}/add?productId=${product.id}`); else router.push("/lists/new"); };
  const archive = () => { if (!selected) return; Alert.alert(`Archive ${product.name}?`, "It will remain in purchase history but cannot be added to new shopping lists.", [{ text: "Cancel", style: "cancel" }, { text: "Archive", style: "destructive", onPress: async () => { await productApi.archive(selected.id, product.id); await qc.invalidateQueries({ queryKey: ["households", selected.id, "products"] }); router.back(); } }]); };
  return <AppScreen><BackHeader title="Product detail" onBack={() => router.back()} right={<SecondaryButton compact label="Edit" fullWidth={false} icon="edit-2" onPress={() => router.push(`/products/edit?id=${product.id}`)} />} />{product.archived_at ? <Text style={styles.archived}>Archived</Text> : null}<View style={[styles.hero, !imageUrl || failedImageUrl === imageUrl ? styles.placeholderHero : null]}>{imageUrl && failedImageUrl !== imageUrl ? <Image onError={() => setFailedImageUrl(imageUrl)} source={{ uri: imageUrl }} style={styles.image} /> : <Feather color={colors.primary} name="package" size={34} />}</View><Text numberOfLines={2} style={styles.name}>{product.name}</Text>{product.brand ? <Text numberOfLines={1} style={styles.brand}>{product.brand}</Text> : null}<Text numberOfLines={2} style={styles.meta}>{[product.variant, formatSize(product.size_value, product.size_unit)].filter(Boolean).join(" · ")}</Text>{product.category ? <Text style={styles.category}>{product.category.display_name}</Text> : null}<SurfaceCard style={styles.usual}><Feather color={colors.primary} name="shopping-cart" size={20} /><Text style={styles.usualText}>Usually buy {formatQuantity(product.usual_quantity)}</Text></SurfaceCard>{product.notes ? <><Text style={styles.section}>Notes</Text><Text style={styles.body}>{product.notes}</Text></> : null}<Text style={styles.section}>Preferred substitute</Text><SurfaceCard style={styles.compactCard}><Text numberOfLines={2} style={styles.body}>{product.preferred_substitutes?.[0]?.substitute_name ?? "No preferred substitute set"}</Text></SurfaceCard><Text style={styles.section}>Purchase summary</Text><SurfaceCard style={styles.summary}><View><Text style={styles.meta}>Last purchased</Text><Text style={styles.body}>{summary.data?.last_purchased_at ? new Date(summary.data.last_purchased_at).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "Not purchased yet"}</Text></View><View><Text style={styles.meta}>Purchased</Text><Text style={styles.body}>{formatQuantity(summary.data?.purchase_count ?? 0)} time{summary.data?.purchase_count === 1 ? "" : "s"}</Text></View></SurfaceCard><View style={styles.actions}>{!product.archived_at ? <PrimaryButton label="Add to shopping list" icon="plus" onPress={add} /> : null}<SecondaryButton label="View purchase history" icon="clock" onPress={() => router.push((`/products/${product.id}/history`) as never)} /><TertiaryButton destructive label="Archive product" icon="archive" onPress={archive} /></View></AppScreen>;
}

const styles = StyleSheet.create({ hero: { height: 156, borderRadius: radius.lg, backgroundColor: colors.primarySubtle, alignItems: "center", justifyContent: "center", overflow: "hidden", marginBottom: spacing.md }, placeholderHero: { height: 112 }, image: { width: "100%", height: "100%" }, name: { ...typography.display, color: colors.text }, brand: { ...typography.body, color: colors.textSecondary, marginTop: spacing.xs }, meta: { ...typography.secondary, color: colors.textSecondary, marginTop: spacing.xs }, category: { alignSelf: "flex-start", ...typography.caption, color: colors.primary, fontWeight: "800", backgroundColor: colors.primarySubtle, borderRadius: radius.round, paddingHorizontal: spacing.md, paddingVertical: spacing.xs, marginTop: spacing.sm }, usual: { flexDirection: "row", alignItems: "center", gap: spacing.sm, marginTop: spacing.md, padding: spacing.md }, usualText: { ...typography.bodyStrong, color: colors.primary }, section: { ...typography.sectionTitle, color: colors.text, marginTop: spacing.lg, marginBottom: spacing.sm }, body: { ...typography.body, color: colors.text }, compactCard: { padding: spacing.md }, summary: { flexDirection: "row", justifyContent: "space-between", padding: spacing.md }, actions: { gap: spacing.sm, marginTop: spacing.md }, archived: { alignSelf: "flex-start", color: colors.warning, backgroundColor: colors.warningSurface, borderRadius: radius.round, paddingHorizontal: spacing.md, paddingVertical: spacing.xs, marginBottom: spacing.sm } });
