import { useLocalSearchParams, useRouter } from "expo-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, StyleSheet, Text, View } from "react-native";
import { AppScreen, BackHeader, InlineError, LoadingState, PrimaryButton, SecondaryButton, SurfaceCard } from "../../src/design/components";
import { colors, spacing, typography } from "../../src/design/theme";
import { useAuth } from "../../src/auth/auth-context";
import { useHouseholds } from "../../src/households/household-context";
import { pushNotificationApi } from "../../src/notifications/api-client";
export default function SubstitutionDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { user } = useAuth(); const { selected } = useHouseholds(); const qc = useQueryClient(); const q = useQuery({ queryKey: ["households", selected?.id, "substitutions", id], queryFn: () => pushNotificationApi.getSubstitution(selected!.id, id), enabled: Boolean(selected && id) }); if (q.isLoading) return <AppScreen><LoadingState rows={4} /></AppScreen>; if (q.isError || !q.data) return <AppScreen><InlineError onRetry={() => void q.refetch()} /><SecondaryButton label="Back" onPress={() => router.back()} /></AppScreen>; const item = q.data; const actionable = item.status === "pending" && item.requested_by_user_id !== user?.id; const decide = async (decision: "approve" | "reject") => { if (!selected) return; try { await pushNotificationApi.decide(selected.id, item.id, decision); await qc.invalidateQueries({ queryKey: ["households", selected.id, "substitutions"] }); } catch (e) { Alert.alert("This request has already been resolved.", e instanceof Error ? e.message : "Refresh to see the latest state."); await q.refetch(); } }; return <AppScreen><BackHeader title="Replacement request" onBack={() => router.back()} /><Text style={styles.label}>Requested item</Text><SurfaceCard><Text style={styles.name}>Trip item</Text><Text style={styles.meta}>This request is tied to the active shopping trip.</Text></SurfaceCard><Text style={styles.label}>Proposed replacement</Text><SurfaceCard><Text style={styles.name}>{item.proposed_name}</Text><Text style={styles.meta}>{[item.proposed_brand, item.proposed_variant, item.proposed_size_value && `${item.proposed_size_value} ${item.proposed_size_unit ?? ""}`].filter(Boolean).join(" · ")}</Text></SurfaceCard><Text style={styles.meta}>Requested by {item.requested_by_user_id}</Text>{item.status === "approved" ? <Text style={styles.success}>Replacement approved</Text> : item.status === "rejected" ? <Text style={styles.rejected}>Replacement rejected</Text> : actionable ? <View style={styles.actions}><SecondaryButton label="Reject" onPress={() => void decide("reject")} /><PrimaryButton label="Approve" onPress={() => void decide("approve")} /></View> : <Text style={styles.waiting}>Waiting for another household member</Text>}</AppScreen>; }
const styles = StyleSheet.create({ label: { ...typography.caption, color: colors.textSecondary, fontWeight: "700", textTransform: "uppercase", marginTop: spacing.lg, marginBottom: spacing.sm }, name: { ...typography.cardTitle, color: colors.text }, meta: { ...typography.secondary, color: colors.textSecondary, marginTop: spacing.xs }, actions: { gap: spacing.sm, marginTop: spacing.xl }, success: { ...typography.bodyStrong, color: colors.success, marginTop: spacing.xl }, rejected: { ...typography.bodyStrong, color: colors.danger, marginTop: spacing.xl }, waiting: { ...typography.bodyStrong, color: colors.warning, marginTop: spacing.xl } });
