/* eslint-disable react/no-unescaped-entities */
import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { Pressable, Text, TextInput, View } from "react-native";
import { useHouseholds } from "../households/household-context";
import { productApi } from "../products/api-client";
import { listApi } from "../lists/api-client";
export function AddListItemScreen(){const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const {selected}=useHouseholds();const qc=useQueryClient();const [search,setSearch]=useState("");const [chosen,setChosen]=useState<any>(null);const [name,setName]=useState("");const [quantity,setQuantity]=useState("1");const products=useQuery({queryKey:["households",selected?.id,"products","list-add",search],queryFn:()=>productApi.list(selected!.id,search?`?query=${encodeURIComponent(search)}`:""),enabled:Boolean(selected&&!chosen)});const add=async()=>{if(!selected||!id)return;await listApi.addItem(selected.id,id,chosen?{household_product_id:chosen.id,requested_quantity:Number(quantity)||1}:{name:name.trim(),requested_quantity:Number(quantity)||1});await qc.invalidateQueries({queryKey:["households",selected.id,"shopping-lists",id]});router.back();};return <View style={{padding:24,paddingTop:80}}><Text style={{fontSize:28,fontWeight:"800"}}>Add item</Text>{!chosen?<><TextInput placeholder="Search household products" value={search} onChangeText={setSearch} style={{backgroundColor:"#fff",padding:14,borderRadius:12,marginTop:20}}/>{products.isLoading?<Text>Searching…</Text>:products.data?.map(p=><Pressable key={p.id} onPress={()=>{setChosen(p);setQuantity(String(p.usual_quantity));}} style={{padding:14,backgroundColor:"#fff",borderRadius:12,marginTop:8}}><Text style={{fontWeight:"700"}}>{p.name}</Text><Text>{p.brand??""} {p.size_value?`${p.size_value} ${p.size_unit??""}`:""} · Usual quantity: {p.usual_quantity}</Text></Pressable>)}<Text style={{marginTop:20}}>Can't find it?</Text><TextInput placeholder="Custom item name" value={name} onChangeText={setName} style={{backgroundColor:"#fff",padding:14,borderRadius:12,marginTop:8}}/></>:<Text style={{marginTop:20,fontSize:18,fontWeight:"700"}}>{chosen.name}</Text>}<TextInput accessibilityLabel="Quantity" placeholder="Quantity" value={quantity} onChangeText={setQuantity} keyboardType="numeric" style={{backgroundColor:"#fff",padding:14,borderRadius:12,marginTop:12}}/><Pressable onPress={()=>void add()} style={{backgroundColor:"#245a43",padding:16,borderRadius:12,marginTop:16,alignItems:"center"}}><Text style={{color:"#fff",fontWeight:"700"}}>Add to list</Text></Pressable></View>}
