import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen, BackHeader, InlineError, LoadingState, PrimaryButton, SecondaryButton, SurfaceCard } from "../design/components";
import { colors, radius, spacing, typography } from "../design/theme";
import { AuthApiError } from "../auth/api-client";
import { useHouseholds } from "../households/household-context";
import { listApi } from "../lists/api-client";
import { productApi } from "../products/api-client";
import type { HouseholdProduct } from "../products/types";

export function AddListItemScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { selected } = useHouseholds(); const qc = useQueryClient();
  const [search, setSearch] = useState(""); const [chosen, setChosen] = useState<HouseholdProduct | null>(null); const [custom, setCustom] = useState(false); const [name, setName] = useState(""); const [quantity, setQuantity] = useState("1"); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const products = useQuery({ queryKey: ["households", selected?.id, "products", "list-add", search], queryFn: () => productApi.list(selected!.id, search ? `?query=${encodeURIComponent(search)}` : ""), enabled: Boolean(selected && !chosen && !custom) });
  const add = async () => { if (!selected || !id || (!chosen && !name.trim())) return; setSaving(true); setError(""); try { await listApi.addItem(selected.id, id, chosen ? { household_product_id: chosen.id, requested_quantity: Number(quantity) || 1, notes: notes.trim() || null } : { name: name.trim(), requested_quantity: Number(quantity) || 1, notes: notes.trim() || null }); await qc.invalidateQueries({ queryKey: ["households", selected.id, "shopping-lists"] }); router.back(); } catch (e) { setError(e instanceof AuthApiError && e.code === "SHOPPING_LIST_PRODUCT_ALREADY_PRESENT" ? "Already on this shopping list" : e instanceof Error ? e.message : "Couldn’t add that item. Try again."); } finally { setSaving(false); } };
  return <AppScreen keyboardSafe><BackHeader title="Add item" subtitle="Find a household product or add a one-off item." onBack={() => router.back()} />{!chosen && !custom ? <><TextInput accessibilityLabel="Search products" autoFocus placeholder="Search household products" value={search} onChangeText={setSearch} style={styles.input} />{products.isLoading ? <LoadingState rows={3} /> : products.isError ? <InlineError onRetry={() => void products.refetch()} /> : <View style={styles.results}>{(products.data ?? []).map(product => <SurfaceCard key={product.id} style={styles.product}><View style={styles.productCopy}><Text style={styles.productName}>{product.name}</Text><Text style={styles.meta}>{[product.brand, product.variant, product.size_value && `${product.size_value} ${product.size_unit ?? ""}`].filter(Boolean).join(" · ") || "Household product"}</Text><Text style={styles.meta}>Usual quantity {product.usual_quantity}</Text></View><SecondaryButton label="Add" icon="plus" fullWidth={false} onPress={() => { setChosen(product); setQuantity(String(product.usual_quantity)); }} /></SurfaceCard>)}</View>}<Text style={styles.prompt}>Can’t find it?</Text><SecondaryButton label="Add custom item" icon="edit-3" onPress={() => setCustom(true)} /></> : <SurfaceCard style={styles.form}><Text style={styles.selectedTitle}>{chosen?.name ?? "Custom item"}</Text>{custom ? <TextInput accessibilityLabel="Item name" autoFocus placeholder="Item name" value={name} onChangeText={setName} style={styles.input} /> : null}<TextInput accessibilityLabel="Quantity" keyboardType="numeric" placeholder="Quantity" value={quantity} onChangeText={setQuantity} style={styles.input} /><TextInput accessibilityLabel="Notes" placeholder="Notes (optional)" value={notes} onChangeText={setNotes} style={styles.input} /><PrimaryButton label="Add to list" icon="check" loading={saving} disabled={custom && !name.trim()} onPress={() => void add()} /><SecondaryButton label="Choose something else" onPress={() => { setChosen(null); setCustom(false); }} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}</SurfaceCard>}</AppScreen>;
}
const styles = StyleSheet.create({ input: { minHeight: 50, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.md, backgroundColor: colors.surface, paddingHorizontal: spacing.md, ...typography.body, color: colors.text, marginBottom: spacing.md }, results: { gap: spacing.sm }, product: { flexDirection: "row", alignItems: "center", gap: spacing.md }, productCopy: { flex: 1 }, productName: { ...typography.cardTitle, color: colors.text }, meta: { ...typography.secondary, color: colors.textSecondary, marginTop: spacing.xs }, prompt: { ...typography.bodyStrong, color: colors.text, marginTop: spacing.xl, marginBottom: spacing.sm }, form: { gap: spacing.md }, selectedTitle: { ...typography.sectionTitle, color: colors.text }, error: { ...typography.secondary, color: colors.danger } });
