import Feather from "@expo/vector-icons/Feather";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { AppScreen, BackHeader, EmptyState, InlineError, LoadingState, PrimaryButton, SurfaceCard } from "../design/components";
import { colors, iconSizes, radius, spacing, typography } from "../design/theme";
import { useHouseholds } from "../households/household-context";
import { householdApiClient } from "../households/api-client";
import { useAuth } from "../auth/auth-context";
export function MembersScreen() { const router = useRouter(); const { selected } = useHouseholds(); const { user } = useAuth(); const q = useQuery({ queryKey: ["households", selected?.id, "members"], queryFn: () => householdApiClient.members(selected!.id), enabled: Boolean(selected) }); return <AppScreen><BackHeader title="Members" subtitle={selected ? `${selected.member_count} people` : undefined} onBack={() => router.back()} />{q.isLoading ? <LoadingState rows={4} /> : q.isError ? <InlineError onRetry={() => void q.refetch()} /> : q.data?.length ? <SurfaceCard style={styles.list}>{q.data.map(member => <View key={member.user_id} style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{(member.display_name || member.email).slice(0, 1).toUpperCase()}</Text></View><View style={styles.copy}><Text style={styles.name}>{member.display_name || member.email}</Text>{member.display_name ? <Text style={styles.email}>{member.email}</Text> : null}<Text style={styles.role}>{member.role === "owner" ? "Owner" : "Member"}{member.user_id === user?.id ? " · You" : ""}</Text></View><Feather color={colors.textSecondary} name="chevron-right" size={iconSizes.md} /></View>)}</SurfaceCard> : <EmptyState icon="users" title="No members found" body="This household does not have any member records yet." />}{selected?.role === "owner" ? <PrimaryButton label="Invite member" icon="user-plus" onPress={() => router.push("/invite")} /> : null}</AppScreen>; }
const styles = StyleSheet.create({ list: { paddingVertical: spacing.xs, marginBottom: spacing.sm }, row: { minHeight: 72, flexDirection: "row", alignItems: "center", gap: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, avatar: { width: 40, height: 40, borderRadius: radius.round, backgroundColor: colors.primarySubtle, alignItems: "center", justifyContent: "center" }, avatarText: { ...typography.bodyStrong, color: colors.primary }, copy: { flex: 1, minWidth: 0 }, name: { ...typography.cardTitle, color: colors.text }, email: { ...typography.secondary, color: colors.textSecondary, marginTop: 2 }, role: { ...typography.caption, color: colors.primary, fontWeight: "700", marginTop: spacing.xs } });
