import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { PixelRatio, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from "react-native";
import { AppHeader, AppScreen, EmptyState, IconButton, InlineError, LoadingState } from "../design/components";
import { colors, radius, spacing, typography } from "../design/theme";
import { useHouseholds } from "../households/household-context";
import { productApi } from "../products/api-client";
import { ProductCard } from "../products/product-components";

export function ProductsScreen() {
  const router = useRouter(); const { selected } = useHouseholds(); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [archived, setArchived] = useState(false);
  const { width } = useWindowDimensions();
  const gridLayout = width >= 360 && PixelRatio.getFontScale() <= 1.2;
  const categories = useQuery({ queryKey: ["product-categories"], queryFn: productApi.categories }); const products = useQuery({ queryKey: ["households", selected?.id, "products", search, category, archived], queryFn: () => productApi.listFiltered(selected!.id, search, category || undefined, archived), enabled: Boolean(selected) });
  return <AppScreen><AppHeader title="Products" subtitle="Your household catalogue." right={<IconButton icon="plus" label="Add product" onPress={() => router.push("/products/new")} />} /><View style={styles.searchWrap}><TextInput accessibilityLabel="Search products" placeholder="Search products" value={search} onChangeText={setSearch} style={styles.search} />{search ? <Pressable accessibilityLabel="Clear search" accessibilityRole="button" onPress={() => setSearch("")} style={styles.clear}><Text>×</Text></Pressable> : null}</View><ScrollView horizontal style={styles.filterRail} contentContainerStyle={styles.chips} showsHorizontalScrollIndicator={false} nestedScrollEnabled>{/* Keep filters in a single compact horizontal rail. */}<Pressable accessibilityRole="button" accessibilityState={{ selected: !category }} onPress={() => setCategory("")} style={[styles.chip, !category ? styles.selectedChip : null]}><Text style={[styles.chipText, !category ? styles.selectedText : null]}>All</Text></Pressable>{(categories.data ?? []).map(item => <Pressable accessibilityRole="button" accessibilityState={{ selected: category === item.id }} key={item.id} onPress={() => setCategory(item.id)} style={[styles.chip, category === item.id ? styles.selectedChip : null]}><Text style={[styles.chipText, category === item.id ? styles.selectedText : null]}>{item.display_name}</Text></Pressable>)}<Pressable accessibilityLabel="Show archived products" accessibilityRole="switch" accessibilityState={{ checked: archived }} onPress={() => setArchived(value => !value)} style={[styles.chip, archived ? styles.selectedChip : null]}><Text style={[styles.chipText, archived ? styles.selectedText : null]}>{archived ? "Archived" : "Active"}</Text></Pressable></ScrollView>{products.isLoading ? <LoadingState rows={5} /> : products.isError ? <InlineError onRetry={() => void products.refetch()} /> : products.data?.length ? <View style={[styles.list, gridLayout ? styles.grid : null]}>{products.data.map(product => <ProductCard key={product.id} layout={gridLayout ? "grid" : "row"} product={product} onPress={() => router.push(`/products/${product.id}`)} />)}</View> : <EmptyState icon="package" title={search || category ? "No products found" : archived ? "No archived products" : "No products yet"} body={search || category ? "Try another name, brand, or category." : "Save the products your household buys regularly so they are faster to add to shopping lists."} action={!search && !category && !archived ? <Pressable accessibilityRole="button" onPress={() => router.push("/products/new")}><Text style={styles.actionText}>Add your first product</Text></Pressable> : null} />}</AppScreen>;
}
const styles = StyleSheet.create({ searchWrap: { position: "relative", marginBottom: spacing.sm }, search: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, backgroundColor: colors.surface, paddingHorizontal: spacing.md, paddingRight: 44, ...typography.body, color: colors.text }, clear: { position: "absolute", right: spacing.xs, top: 2, width: 44, height: 44, alignItems: "center", justifyContent: "center" }, filterRail: { height: 40, flexGrow: 0, marginBottom: spacing.lg }, chips: { alignItems: "center", gap: spacing.sm, paddingRight: spacing.md }, chip: { height: 34, paddingHorizontal: spacing.md, borderRadius: radius.round, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, selectedChip: { backgroundColor: colors.primary }, chipText: { ...typography.secondary, color: colors.text }, selectedText: { color: colors.surface, fontWeight: "700" }, list: { gap: spacing.sm }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, actionText: { ...typography.bodyStrong, color: colors.primary, paddingVertical: spacing.md } });
