"""purchases and trip completion"""
# ruff: noqa
import sqlalchemy as sa
from alembic import op
revision="0008_purchases"; down_revision="0007_substitution_requests"; branch_labels=None; depends_on=None
def upgrade():
    op.add_column("shopping_trips", sa.Column("completed_at", sa.DateTime(timezone=True)))
    op.drop_constraint("ck_shopping_trips_status", "shopping_trips", type_="check")
    op.create_check_constraint("ck_shopping_trips_status", "shopping_trips", "status IN ('active','cancelled','completed')")
    op.create_table("purchases", sa.Column("id",sa.Uuid(),primary_key=True), sa.Column("household_id",sa.Uuid(),sa.ForeignKey("households.id",ondelete="CASCADE"),nullable=False), sa.Column("shopping_trip_id",sa.Uuid(),sa.ForeignKey("shopping_trips.id",ondelete="RESTRICT"),nullable=False), sa.Column("trip_item_id",sa.Uuid(),sa.ForeignKey("trip_items.id",ondelete="RESTRICT"),nullable=False,unique=True), sa.Column("household_product_id",sa.Uuid(),sa.ForeignKey("household_products.id",ondelete="SET NULL")), sa.Column("requested_name_snapshot",sa.String(160),nullable=False), sa.Column("requested_brand_snapshot",sa.String(120)), sa.Column("requested_variant_snapshot",sa.String(160)), sa.Column("requested_size_value_snapshot",sa.Numeric(12,3)), sa.Column("requested_size_unit_snapshot",sa.String(24)), sa.Column("purchased_name_snapshot",sa.String(160),nullable=False), sa.Column("purchased_brand_snapshot",sa.String(120)), sa.Column("purchased_variant_snapshot",sa.String(160)), sa.Column("purchased_size_value_snapshot",sa.Numeric(12,3)), sa.Column("purchased_size_unit_snapshot",sa.String(24)), sa.Column("requested_quantity",sa.Numeric(12,3),nullable=False), sa.Column("purchased_quantity",sa.Numeric(12,3),nullable=False), sa.Column("unit_price",sa.Numeric(12,2)), sa.Column("total_price",sa.Numeric(12,2)), sa.Column("substituted",sa.Boolean(),nullable=False,server_default="false"), sa.Column("purchased_by_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False), sa.Column("purchased_at",sa.DateTime(timezone=True),nullable=False), sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()")), sa.CheckConstraint("requested_quantity > 0",name="ck_purchases_requested_quantity"), sa.CheckConstraint("purchased_quantity > 0",name="ck_purchases_purchased_quantity"), sa.CheckConstraint("unit_price IS NULL OR unit_price >= 0",name="ck_purchases_unit_price"), sa.CheckConstraint("total_price IS NULL OR total_price >= 0",name="ck_purchases_total_price"))
    op.create_index("ix_purchases_household_purchased_at","purchases",["household_id","purchased_at"]); op.create_index("ix_purchases_household_product","purchases",["household_id","household_product_id"])
def downgrade():
    op.drop_table("purchases"); op.drop_constraint("ck_shopping_trips_status", "shopping_trips", type_="check"); op.create_check_constraint("ck_shopping_trips_status", "shopping_trips", "status IN ('active','cancelled')"); op.drop_column("shopping_trips","completed_at")
