import Feather from "@expo/vector-icons/Feather";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { AppHeader, AppScreen, AppTopBar, EmptyState, InlineError, LoadingState, SurfaceCard } from "../../../src/design/components";
import { colors, iconSizes, radius, spacing, typography } from "../../../src/design/theme";
import { useHouseholds } from "../../../src/households/household-context";
import { useAuth } from "../../../src/auth/auth-context";
import { purchasesApi } from "../../../src/purchases/api-client";
import { PurchaseRow } from "../../../src/purchases/purchase-components";
export default function HistoryScreen() { const router = useRouter(); const { user } = useAuth(); const { selected } = useHouseholds(); const q = useQuery({ queryKey: ["households", selected?.id, "purchases", "preview"], queryFn: () => purchasesApi.list(selected!.id, 0), enabled: Boolean(selected) }); return <AppScreen><AppTopBar initials={user?.display_name || user?.email || "U"} onNotifications={() => router.push("/substitutions")} onProfile={() => router.push("/profile")} /><AppHeader title="History" subtitle="Keep track of what your household buys." />{q.isLoading ? <LoadingState rows={3} /> : q.isError ? <InlineError onRetry={() => void q.refetch()} /> : <><Pressable accessibilityRole="button" onPress={() => router.push("/purchases")}><SurfaceCard style={styles.card}><View style={styles.icon}><Feather color={colors.primary} name="file-text" size={iconSizes.md} /></View><View style={styles.copy}><Text style={styles.title}>Purchase History</Text><Text style={styles.body}>See everything your household has bought, organized by date.</Text><Text style={styles.meta}>{q.data?.length ?? 0} recent purchases</Text></View><Feather color={colors.textSecondary} name="chevron-right" size={iconSizes.md} /></SurfaceCard></Pressable><Pressable accessibilityRole="button" onPress={() => router.push("/purchasing-memory")}><SurfaceCard style={styles.card}><View style={styles.icon}><Feather color={colors.primary} name="repeat" size={iconSizes.md} /></View><View style={styles.copy}><Text style={styles.title}>Purchasing Memory</Text><Text style={styles.body}>Quickly find things your household buys repeatedly.</Text><Text style={styles.meta}>Recent and frequent products</Text></View><Feather color={colors.textSecondary} name="chevron-right" size={iconSizes.md} /></SurfaceCard></Pressable>{q.data?.length ? <><Text style={styles.recent}>Recent activity</Text>{q.data.slice(0, 3).map(item => <PurchaseRow key={item.id} purchase={item} onPress={item.household_product_id ? () => router.push(`/products/`) : undefined} />)}</> : <EmptyState icon="clock" title="No purchase activity yet" body="Complete a shopping trip to start building your household history." />}</>}</AppScreen>; }
const styles = StyleSheet.create({ card: { minHeight: 96, flexDirection: "row", alignItems: "center", gap: spacing.md, marginBottom: spacing.md }, icon: { width: 46, height: 46, borderRadius: radius.md, backgroundColor: colors.primarySubtle, alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, title: { ...typography.cardTitle, color: colors.text }, body: { ...typography.secondary, color: colors.textSecondary, marginTop: spacing.xs }, meta: { ...typography.caption, color: colors.primary, marginTop: spacing.sm }, recent: { ...typography.sectionTitle, color: colors.text, marginTop: spacing.xl, marginBottom: spacing.sm }, activity: { ...typography.body, color: colors.text, paddingVertical: spacing.sm } });
