import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAuth } from "../../src/auth/auth-context";
import { useHouseholds } from "../../src/households/household-context";
import { CreateHouseholdScreen } from "../../src/screens/create-household-screen";
import { LoadingScreen } from "../../src/components/loading-screen";
export default function HomeScreen(){const router=useRouter();const {user,logout}=useAuth();const {loading,households,selected}=useHouseholds();if(loading)return <LoadingScreen/>;if(!households.length)return <CreateHouseholdScreen/>;return <SafeAreaView style={styles.screen}><View style={styles.content}><Text style={styles.kicker}>HOUSEHOLD SHOPPING</Text><Text style={styles.title}>{selected?.name}</Text><Text style={styles.body}>Signed in as {user?.display_name}</Text><Text style={styles.note}>{selected?.member_count} member{selected?.member_count===1?"":"s"} · {selected?.role}</Text><Pressable onPress={()=>router.push("/members")} style={styles.button}><Text style={styles.buttonText}>View members</Text></Pressable><Pressable onPress={()=>router.push("/households")} style={styles.button}><Text style={styles.buttonText}>Switch household</Text></Pressable><Pressable onPress={()=>void logout()} style={styles.button}><Text style={styles.buttonText}>Log out</Text></Pressable></View></SafeAreaView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f7f4ed"},content:{flex:1,justifyContent:"center",padding:24},kicker:{color:"#245a43",fontWeight:"800",letterSpacing:1},title:{color:"#15251b",fontSize:32,fontWeight:"800",marginTop:12},body:{color:"#26352c",fontSize:18,fontWeight:"600",marginTop:10},note:{color:"#5b685f",fontSize:16,marginTop:8},button:{minHeight:52,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#9aaba0",borderRadius:12,marginTop:16},buttonText:{color:"#245a43",fontSize:16,fontWeight:"700"}});
